import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import RootNavigation from '@/components/layout/navigation/RootNavigation'

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex w-[95%] mx-auto bg-[#F7F8FA]'>
          <div>
            <RootNavigation >
              {children}
            </RootNavigation>
          </div>
        </div>
      </body>
    </html>
  )
}
